### ISSUE TITLE
Problem with network_mode: "host' on docker-compose

### ISSUE THREAD

**Issue by ffroliva** [confluentinc/cp-demo#137]
hi,

I'm working with this demo and it is working fine.
However, I'm now creating a new source connector who accesses an API over the internet.
the docker-compose does not have `network_mode: "host"` configured for any of the cotainers defined in it. 

I have tryed to set `network_mode: "host"` only on the `connect` container config as below:

```
connect:
    image: confluentinc/cp-kafka-connect:5.3.1
    container_name: connect
    cpus: 0.6
    restart: always
    ports:
      - "8083:8083"
    network_mode: "host"
    depends_on:
      - zookeeper
      - kafka1
      - kafka2
      - schemaregistry
...
```

Unfortunately, when I run the `./script/start.sh` and check the `docker logs connect --follow` I am getting the error below:

```
[main] ERROR io.confluent.admin.utils.cli.KafkaReadyCommand - Error while running kafka-ready.
org.apache.kafka.common.KafkaException: Failed to create new KafkaAdminClient
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:407)
	at org.apache.kafka.clients.admin.AdminClient.create(AdminClient.java:65)
	at io.confluent.admin.utils.ClusterStatus.isKafkaReady(ClusterStatus.java:138)
	at io.confluent.admin.utils.cli.KafkaReadyCommand.main(KafkaReadyCommand.java:150)
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:88)
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:47)
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:367)
	... 3 more
```

can anyone help me to configure the docker-compose so my source connector can access the internet?

Thank you in advance.

Best regards,

Flávio Oliva

**Comment by javabrett** [comment]
`network_mode: "host"` shouldn't be used or required for internet access - the default `bridge` networking and driver should work fine.  The default `cp-demo` build in-fact reads from internet for Wikipedia/Wikimedia recentchanges stream.

If you are having internet access problems it is likely a local firewall/proxy or other Docker daemon configuration problem.
