### ISSUE TITLE
cp-demo: Multiple warnings : WARN[0000] On multiple settings

### ISSUE THREAD

**Issue by Elizabeth030483** [confluentinc/cp-demo#389]
Hello,
I have been using cp-demo last couple of times successfully, but on 6.2 it is giving me below list of warnings. Due to which some of the services not working. 
**1st time when I saw the same warnings**:
1) Control Center was not showing the replicator
2) Simply I have shutdown the cp-demo and removed the docker container cleanly
3) Re-installed cp-demo
**2nd time when I re-installed and restarted cp-demo, I saw the same warnings**
1) This time, Control center not even launching at localhost:9021

Am I missing anything?

Liz's MacBook$  docker-compose ps
WARN[0000] The "SSL_CIPHER_SUITES" variable is not set. Defaulting to a blank string. 
WARN[0000] The "CONNECTOR_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "CONNECTOR_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "SSL_CIPHER_SUITES" variable is not set. Defaulting to a blank string. 
WARN[0000] The "SSL_CIPHER_SUITES" variable is not set. Defaulting to a blank string. 
WARN[0000] The "SSL_CIPHER_SUITES" variable is not set. Defaulting to a blank string. 
WARN[0000] The "REPOSITORY" variable is not set. Defaulting to a blank string. 
WARN[0000] The "REPOSITORY" variable is not set. Defaulting to a blank string. 
WARN[0000] The "SSL_CIPHER_SUITES" variable is not set. Defaulting to a blank string. 
WARN[0000] The "REPOSITORY" variable is not set. Defaulting to a blank string. 
WARN[0000] The "REPOSITORY" variable is not set. Defaulting to a blank string. 
WARN[0000] The "SSL_CIPHER_SUITES" variable is not set. Defaulting to a blank string. 
WARN[0000] The "SSL_CIPHER_SUITES" variable is not set. Defaulting to a blank string. 
WARN[0000] The "CONTROL_CENTER_KSQL_WIKIPEDIA_ADVERTISED_URL" variable is not set. Defaulting to a blank string. 
WARN[0000] The "CONTROL_CENTER_KSQL_WIKIPEDIA_URL" variable is not set. Defaulting to a blank string. 
WARN[0000] The "REPOSITORY" variable is not set. Defaulting to a blank string. 
WARN[0000] The "SSL_CIPHER_SUITES" variable is not set. Defaulting to a blank string. 
WARN[0000] The "SSL_CIPHER_SUITES" variable is not set. Defaulting to a blank string. 
WARN[0000] The "SSL_CIPHER_SUITES" variable is not set. Defaulting to a blank string. 
WARN[0000] The "REPOSITORY" variable is not set. Defaulting to a blank string. 
WARN[0000] The "REPOSITORY" variable is not set. Defaulting to a blank string. 
WARN[0000] The "SSL_CIPHER_SUITES" variable is not set. Defaulting to a blank string. 
WARN[0000] The "SSL_CIPHER_SUITES" variable is not set. Defaulting to a blank string. 
WARN[0000] The "REPOSITORY" variable is not set. Defaulting to a blank string. 
NAME                COMMAND                  SERVICE             STATUS              PORTS
connect             "/etc/confluent/dock…"   connect             running             0.0.0.0:8083->8083/tcp, :::8083->8083/tcp, 9092/tcp
control-center      "/etc/confluent/dock…"   control-center      running             0.0.0.0:9021->9021/tcp, :::9021->9021/tcp, 0.0.0.0:9022->9022/tcp, :::9022->9022/tcp
kafka1              "bash -c 'if [ ! -f …"   kafka1              running             0.0.0.0:8091->8091/tcp, :::8091->8091/tcp, 0.0.0.0:9091->9091/tcp, :::9091->9091/tcp, 9092/tcp, 0.0.0.0:10091->10091/tcp, :::10091->10091/tcp, 0.0.0.0:11091->11091/tcp, :::11091->11091/tcp, :::12091->12091/tcp, 0.0.0.0:12091->12091/tcp
kafka2              "bash -c 'if [ ! -f …"   kafka2              running             0.0.0.0:8092->8092/tcp, :::8092->8092/tcp, 0.0.0.0:9092->9092/tcp, :::9092->9092/tcp, 0.0.0.0:10092->10092/tcp, :::10092->10092/tcp, 0.0.0.0:11092->11092/tcp, :::11092->11092/tcp, 0.0.0.0:12092->12092/tcp, :::12092->12092/tcp
openldap            "/container/tool/run…"   openldap            running             0.0.0.0:389->389/tcp, :::389->389/tcp, 636/tcp
schemaregistry      "/etc/confluent/dock…"   schemaregistry      running             8081/tcp, 0.0.0.0:8085->8085/tcp, :::8085->8085/tcp
tools               "/bin/bash"              tools               running             
zookeeper           "/etc/confluent/dock…"   zookeeper           running             0.0.0.0:2181->2181/tcp, :::2181->2181/tcp, 0.0.0.0:2182->2182/tcp, :::2182->2182/tcp, 2888/tcp, 3888/tcp
Liz's MacBook$  date
Sat Sep 25 16:38:08 PDT 2021
Liz's MacBook$  

Thanks,
Liz.

**Comment by Elizabeth030483** [comment]
**Docker logs for Confluent Center**:

[2021-09-25 23:36:14,140] ERROR [main] Failed to authenticate (org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule)
java.io.IOException: Failed to authenticate
	at io.confluent.kafka.clients.plugins.auth.token.AbstractTokenLoginCallbackHandler.handle(AbstractTokenLoginCallbackHandler.java:102)
	at org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule.identifyToken(OAuthBearerLoginModule.java:316)
	at org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule.login(OAuthBearerLoginModule.java:301)
	at java.base/javax.security.auth.login.LoginContext.invoke(LoginContext.java:726)
	at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:665)
	at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:663)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:663)
	at java.base/javax.security.auth.login.LoginContext.login(LoginContext.java:574)
	at org.apache.kafka.common.security.oauthbearer.internals.expiring.ExpiringCredentialRefreshingLogin.login(ExpiringCredentialRefreshingLogin.java:204)
	at org.apache.kafka.common.security.oauthbearer.internals.OAuthBearerRefreshingLogin.login(OAuthBearerRefreshingLogin.java:150)
	at org.apache.kafka.common.security.authenticator.LoginManager.<init>(LoginManager.java:62)
	at org.apache.kafka.common.security.authenticator.LoginManager.acquireLoginManager(LoginManager.java:105)
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:176)
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:198)
	at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:82)
	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:120)
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:553)
	at org.apache.kafka.clients.admin.Admin.create(Admin.java:144)
	at org.apache.kafka.clients.admin.AdminClient.create(AdminClient.java:49)
	at io.confluent.admin.utils.ClusterStatus.isKafkaReady(ClusterStatus.java:138)
	at io.confluent.admin.utils.cli.KafkaReadyCommand.main(KafkaReadyCommand.java:150)
Caused by: org.apache.kafka.common.errors.AuthenticationException: Failed to authenticate
Caused by: org.apache.kafka.common.errors.TimeoutException: Request aborted due to timeout.
[2021-09-25 23:36:14,142] ERROR [pool-2-thread-1] Error while refreshing active metadata server urls, retrying (io.confluent.security.auth.client.rest.RestClient)
org.apache.kafka.common.errors.TimeoutException: Request aborted due to timeout.
[2021-09-25 23:36:14,179] ERROR [main] Error while running kafka-ready. (io.confluent.admin.utils.cli.KafkaReadyCommand)
org.apache.kafka.common.KafkaException: Failed to create new KafkaAdminClient
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:586)
	at org.apache.kafka.clients.admin.Admin.create(Admin.java:144)
	at org.apache.kafka.clients.admin.AdminClient.create(AdminClient.java:49)
	at io.confluent.admin.utils.ClusterStatus.isKafkaReady(ClusterStatus.java:138)
	at io.confluent.admin.utils.cli.KafkaReadyCommand.main(KafkaReadyCommand.java:150)
Caused by: org.apache.kafka.common.KafkaException: javax.security.auth.login.LoginException: An internal error occurred while retrieving token from callback handler
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:190)
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:198)
	at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:82)
	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:120)
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:553)
	... 4 more
Caused by: javax.security.auth.login.LoginException: An internal error occurred while retrieving token from callback handler
	at org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule.identifyToken(OAuthBearerLoginModule.java:319)
	at org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule.login(OAuthBearerLoginModule.java:301)
	at java.base/javax.security.auth.login.LoginContext.invoke(LoginContext.java:726)
	at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:665)
	at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:663)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:663)
	at java.base/javax.security.auth.login.LoginContext.login(LoginContext.java:574)
	at org.apache.kafka.common.security.oauthbearer.internals.expiring.ExpiringCredentialRefreshingLogin.login(ExpiringCredentialRefreshingLogin.java:204)
	at org.apache.kafka.common.security.oauthbearer.internals.OAuthBearerRefreshingLogin.login(OAuthBearerRefreshingLogin.java:150)
	at org.apache.kafka.common.security.authenticator.LoginManager.<init>(LoginManager.java:62)
	at org.apache.kafka.common.security.authenticator.LoginManager.acquireLoginManager(LoginManager.java:105)
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:176)
	... 8 more
Liz's MacBook$

**Comment by Elizabeth030483** [comment]
Any comments on this is appreciated.

**Comment by chuck-confluent** [comment]
Hey @Elizabeth030483, CP Demo is started with `./scripts/start.sh`, which sources a bunch of environment variables before running `docker-compose up`. You're seeing those warnings because you don't have those environment variables loaded into your shell. You can either run the start script or you can `(cd scripts && source ./env.sh)` to load those environment variables into your shell. I hope that helps!
